### ISSUE TITLE
Definitions for global variables and undocumented arguments

### ISSUE THREAD

**Issue by MargaretSiple-NOAA** [alaska-groundfish-efh/EFHSDM#8]
I ran `devtools::check()` in the console for the pkgdev branch and it brings up several areas where we'll need to clean up the namespaces and function documentation. Here is just the start of it:
![image](https://user-images.githubusercontent.com/73858992/159565861-165af5b6-79f1-4af1-8dda-309bfd9e5164.png)

Quick fixes for what the `devtools::check()` diagnostics are looking at, in order of the importance of addressing them:

- "no visible global function definition" --> need to add namespace prefix, e.g., `raster::raster(` instead of `raster(`
- "Undocumented arguments in documentation object" --> Check Roxygen2 code to make sure each input for the function has some text after it. If it's a deprecated function and it's not worth writing real descriptions for those variables, you can just write "deprecated" in the description.
- "Undocumented datasets" --> Make a file in the `R/` directory called `variableX-data.R` with a format that looks like [this](https://github.com/alaska-groundfish-efh/EFHSDM/blob/pkgdev/R/GOA_bathy-data.R), where `variableX` is the name of the dataset object. When you run `devtools::document()`, roxygen2 will automatically write a .Rd help file for that dataset. Then you commit and push both the .R and the .Rd file to github.

In general, my workflow is usually to run `devtools::check()`, fix what I can see that needs fixing, then run it again and see what else needs to get done. `devtools::check()` is pretty picky; there will be just a few things that we won't fix that that function can check.

**Comment by jeremyharris7** [comment]
Hi,

So, one of the problems here is that we are hitting a lot of the bits that I've been wanting to deprecate. Rather than solve a lot of these, problems, I'd rather just start deleting. However, before I ought to do that, I would need to check that I have a new script "Meatgrinder6" or something that is still functional. Said script is in progress. How should we proceed? Should I focus on trying to fix the those parts, or do you want to just comment them out for now? I can have a new version up and running probably by friday.

I've been having trouble getting the package to actually build, and so haven't been able to load. I've trying to run some updates in the hopes that will solve things, but I might need help there. 

Last, a few of these errors are confusing. the functions legend() and as.formula() are in basic R, like stats and base. Does literally every function (like even sum() ) or things like that need a reference?

**Comment by MargaretSiple-NOAA** [comment]
Right; we talked about those deprecated ones when we started. I think starting to delete is fine, especially if none of the examples depend on those functions. You're right though, we do want to retain a `Meatgrinder.R` script that works with the full set we keep. You can definitely just comment out the deprecated functions for now and keep working on MG6.

I have also noticed that `devtools` flags really basic functions. If they are functions from base R, you do not need to add a `packagename::` prefix to them. But if they're from `stats` those should have a `stats::` prefix. I honestly can't remember why, but I remember it from the last package I worked on. 

When I get a minute (prob not till tomorrow) I'll try installing it on a brand new machine and see if I can get it to build. I haven't done that yet, but should have more to contribute in a day or so.

**Comment by MargaretSiple-NOAA** [comment]
According to Sean, we don't need to add definitions for global variables, but we do have to add them for all the functions that didn't have global definitions (e.g., all the `terra` functions). I'm going to close this because I think we've dealt with it!
